package com.redhat.bpms.examples.mortgage;

rule "Retract Applicant after Calculation"
	dialect "mvel"
	ruleflow-group "apr-calculation"
	salience -10
	when
		fact : Applicant( )
	then
		retract(fact);
		System.out.println("Executed Rule: " + drools.getRule().getName() );
end

rule "Retract Application after Calculation"
	dialect "mvel"
	ruleflow-group "apr-calculation"
	salience -10
	when
		fact : Application( )
	then
		retract(fact);
		System.out.println("Executed Rule: " + drools.getRule().getName() );
end

rule "Retract Appraisal after Calculation"
	dialect "mvel"
	ruleflow-group "apr-calculation"
	salience -10
	when
		fact : Appraisal( )
	then
		retract(fact);
		System.out.println("Executed Rule: " + drools.getRule().getName() );
end

rule "Retract Property after Calculation"
	dialect "mvel"
	ruleflow-group "apr-calculation"
	salience -10
	when
		fact : Property( )
	then
		retract(fact);
		System.out.println("Executed Rule: " + drools.getRule().getName() );
end
